apiVersion: v1
data:
  install_plugins.sh: cd /opt/sonarqube/extensions/plugins/tmp
kind: ConfigMap
metadata:
  labels:
    app: sonarqube
    release: sonarqube
  name: sonarqube-sonarqube-install-plugins