apiVersion: v1
data:
  run.sh: |-
    @test "Testing Sonarqube UI is accessible" {
      curl --connect-timeout 5 --retry 12 --retry-delay 1 --retry-max-time 60 sonarqube-sonarqube:9000/sessions/new
    }
kind: ConfigMap
metadata:
  labels:
    app: sonarqube
    release: sonarqube
  name: sonarqube-sonarqube-tests
