apiVersion: v1
data:
  SONAR_JDBC_PASSWORD: c29uYXJkYjEyMw==
  SONARQUBE_JDBC_PASSWORD: c29uYXJkYjEyMw==
kind: Secret
metadata:
  labels:
    app: sonarqube
    release: sonarqube
  name: sonarqube-secret
