# Exemplo: Desabilitar initContainers
# Use este arquivo para instalar o chart sem os initContainers

sonarqube:
  initContainers:
    initVmMaxMapCount:
      enabled: false
    downloadPlugins:
      enabled: false

postgresql:
  initContainers:
    fixPermissions:
      enabled: false
