{{- if .Values.sonarqube.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sonarqube.name }}-env
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  SONARQUBE_WEB_HOST: "{{ .Values.sonarqube.env.webHost }}"
  SONARQUBE_JDBC_USERNAME: "{{ .Values.sonarqube.env.jdbcUsername }}"
  SONAR_JDBC_USERNAME: "{{ .Values.sonarqube.env.jdbcUsername }}"
  SONAR_JDBC_URL: jdbc:postgresql://{{ .Values.postgresql.name }}-db-{{ .Values.postgresql.name }}:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.env.database }}
  SONARQUBE_JDBC_URL: jdbc:postgresql://{{ .Values.postgresql.name }}-db-{{ .Values.postgresql.name }}:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.env.database }}
  SONAR_WEB_JAVAOPTS: "{{ .Values.sonarqube.env.webJavaOpts }}"
  SONAR_CE_JAVAOPTS: "{{ .Values.sonarqube.env.ceJavaOpts }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sonarqube.name }}-copy-plugins
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  copy_plugins.sh: |
    #!/bin/bash
    for f in /opt/sonarqube/extensions/plugins/tmp/*.jar
    do
      file=${f##*/} && file=${file%-[0-9]*}
      for original in /opt/sonarqube/extensions/plugins/*.jar
      do
        originalfile=${original##*/} && originalfile=${originalfile%-[0-9]*}
        if [ "$originalfile" = "$file" ]; then
          rm -f "$original"
        fi
      done
    done
    cp /opt/sonarqube/extensions/plugins/tmp/*.jar /opt/sonarqube/extensions/plugins/
    /opt/sonarqube/bin/run.sh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sonarqube.name }}-install-plugins
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  install_plugins.sh: cd /opt/sonarqube/extensions/plugins/tmp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sonarqube.name }}-tests
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  run.sh: |-
    @test "Testing Sonarqube UI is accessible" {
      curl --connect-timeout 5 --retry 12 --retry-delay 1 --retry-max-time 60 {{ .Values.sonarqube.name }}-{{ .Values.sonarqube.name }}:{{ .Values.sonarqube.service.port }}/sessions/new
    }
{{- end }}
