{{- if .Values.sonarqube.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sonarqube.name }}-{{ .Values.sonarqube.name }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.sonarqube.name }}
    port: {{ .Values.sonarqube.service.port }}
    protocol: TCP
    targetPort: {{ .Values.sonarqube.service.port }}
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.sonarqube.service.type }}
{{- end }}
