{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sonarqube.name }}-db-{{ .Values.postgresql.name }}
  labels:
    app: {{ .Values.postgresql.name }}
    release: sonar-db
spec:
  ports:
  - name: {{ .Values.postgresql.name }}
    port: {{ .Values.postgresql.service.port }}
    protocol: TCP
    targetPort: {{ .Values.postgresql.name }}
  selector:
    app: {{ .Values.postgresql.name }}
    release: sonar-db
    role: master
  sessionAffinity: None
  type: {{ .Values.postgresql.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-db-{{ .Values.postgresql.name }}-headless
  labels:
    app: {{ .Values.postgresql.name }}
    release: sonar-db
spec:
  clusterIP: None
  ports:
  - name: {{ .Values.postgresql.name }}
    port: {{ .Values.postgresql.service.port }}
    protocol: TCP
    targetPort: {{ .Values.postgresql.name }}
  selector:
    app: {{ .Values.postgresql.name }}
    release: sonar-db
  sessionAffinity: None
  type: ClusterIP
{{- end }}
