{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.sonarqube.name }}-db-{{ .Values.postgresql.name }}
  labels:
    app: {{ .Values.postgresql.name }}
    release: sonar-db
spec:
  replicas: {{ .Values.postgresql.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.postgresql.name }}
      release: sonar-db
      role: master
  serviceName: sonar-db-{{ .Values.postgresql.name }}-headless
  template:
    metadata:
      name: sonar-db-{{ .Values.postgresql.name }}
      labels:
        app: {{ .Values.postgresql.name }}
        release: sonar-db
        role: master
    spec:
      {{- if .Values.postgresql.initContainers.fixPermissions.enabled }}
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /var/lib/postgresql"]
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsUser: 0
      {{- end }}
      containers:
        - name: sonar-db-{{ .Values.postgresql.name }}
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.postgresql.name }}-{{ .Values.sonarqube.name }}-env
            - secretRef:
                name: sonar-db-{{ .Values.postgresql.name }}
          ports:
            - containerPort: {{ .Values.postgresql.service.port }}
              name: {{ .Values.postgresql.name }}
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "{{ .Values.postgresql.env.user }}" -d "{{ .Values.postgresql.env.database }}" -h 127.0.0.1 -p {{ .Values.postgresql.service.port }}
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          securityContext:
            runAsUser: {{ .Values.postgresql.securityContext.runAsUser }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: {{ .Values.postgresql.securityContext.fsGroup }}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.sonarqube.name }}-db-{{ .Values.postgresql.name }}-pvc
  updateStrategy:
    type: RollingUpdate
{{- end }}
