{{- if and .Values.sonarqube.enabled .Values.sonarqube.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.sonarqube.name }}-ingress
  annotations:
    {{- toYaml .Values.sonarqube.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.sonarqube.ingress.className }}
  rules:
    - host: {{ .Values.sonarqube.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.sonarqube.name }}-{{ .Values.sonarqube.name }}
                port:
                  number: {{ .Values.sonarqube.service.port }}
            path: /
            pathType: ImplementationSpecific
{{- end }}
