{{- if .Values.sonarqube.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sonarqube.name }}-secret
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
type: Opaque
data:
  SONAR_JDBC_PASSWORD: {{ .Values.sonarqube.jdbcPassword }}
  SONARQUBE_JDBC_PASSWORD: {{ .Values.sonarqube.jdbcPassword }}
{{- end }}
