apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    release: sonar-db
  name: sonarqube-db-postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
    release: sonar-db
    role: master
  sessionAffinity: None
  type: ClusterIP
