apiVersion: v1
data:
  postgresql-password: c29uYXJkYjEyMw==
  POSTGRES_PASSWORD: c29uYXJkYjEyMw==
kind: Secret
metadata:
  labels:
    app: postgresql
    release: sonar-db
  name: sonar-db-postgresql